# Generated by Django 5.1.6 on 2025-03-17 22:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "apt_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("apt_number", models.CharField(max_length=5, unique=True)),
                ("apt_type", models.CharField(max_length=15)),
                ("available_permits", models.PositiveSmallIntegerField(default=5)),
                ("address_line1", models.CharField(max_length=35)),
                ("address_line2", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(max_length=15)),
                ("state", models.CharField(max_length=2)),
                ("zipcode", models.CharField(max_length=5)),
            ],
        ),
    ]
