# Generated by Django 5.1.6 on 2025-03-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_apartment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="address_line1",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="address_line2",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="city",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="state",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="zipcode",
        ),
    ]
