# Generated by Django 5.1.6 on 2025-03-17 22:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_apartment_address_line1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "lease_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("lease_created", models.DateTimeField(auto_now_add=True)),
                ("lease_signed", models.DateTimeField(auto_now=True)),
                ("lease_end", models.DateField()),
                (
                    "apartment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.apartment"
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.landlord"
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.tenant",
                    ),
                ),
            ],
        ),
    ]
