# Generated by Django 5.0.1 on 2025-03-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_complaint_complaint_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keycode",
            name="apartment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.apartment"
            ),
        ),
    ]
