# Generated by Django 5.0.1 on 2025-03-25 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_keycode_apartment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complaint",
            old_name="apartment",
            new_name="complainer",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="landlord",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="tenant",
        ),
        migrations.AddField(
            model_name="complaint",
            name="complaint_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
