# Generated by Django 5.1.6 on 2025-03-17 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_lease"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="is_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lease",
            name="lease_signed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complaint_title", models.CharField(max_length=25)),
                ("complaint_desc", models.TextField(blank=True, null=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.apartment"
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.landlord"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Keycode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_generated", models.DateTimeField(auto_now_add=True)),
                ("key", models.PositiveIntegerField(default=130762)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.apartment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivered_time", models.DateTimeField(auto_now_add=True)),
                ("picked_up_time", models.DateTimeField(blank=True, null=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.apartment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_parking", models.BooleanField(default=False)),
                ("license_plate", models.CharField(max_length=7, unique=True)),
                ("car_model", models.CharField(max_length=15)),
                ("created_time", models.DateField(auto_now_add=True)),
                ("end_time", models.DateField(null=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.apartment"
                    ),
                ),
            ],
        ),
    ]
